name: Selex-X-Genome
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - pandas
  - jupyterlab
  - requests
  - bedtools=2.31.1
  - samtools=1.19.2
  - bowtie2=2.5.3
  - biopython